# =====================================================
# Data displayed on the Home (About Me) page.
#
# üí° Tip for Images / Logo:
# You can use either:
# 1. A full URL (e.g., https://example.com/logo.png)
# 2. A local file placed under /public/images/ and referenced with "/" (e.g., "/images/logo.png")
# =====================================================

# =====================================================
# üë§ Personal Information
# =====================================================

profile:
  name: "Victoria Chernobay"
  headline: "Student @ Toronto Metropolitan University"
  email: "chernobayv05@gmail.com"
  location: "Toronto, ON"
  profileImage: "https://github.com/pm25.png"

  links:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/chernobayv"
      icon:
        name: "FaLinkedin"
        package: "react-icons/fa6"

    - name: "R√©sum√©"
      url: "/pdf/sample-resume.pdf"
      icon:
        name: "FaRegIdBadge"
        package: "react-icons/fa6"

    - name: "Github"
      url: "https://github.com/chernobayv"
      icon:
        name: "FaGithub"
        package: "react-icons/fa6"


  # you can use HTML syntax here (e.g. <br/>, <a>, <strong>, ...)
  biography: |
    Hi! I'm <strong>Victoria</strong>, an <em>engineering student</em> passionate about <em>new and emerging tech</em>. Currently, I work as <em>a Physical AI Intern</em> at <em>SAP</em>, where I <em>am developing an AI powered solution for manufacturing</em>. 
    With a background in <em>robotics and team management</em>, I've developed strong interests in <em>automation, space, and physics</em>.
    Outside of work, I enjoy <em>art and music</em>, which inspire creativity and keep me energized. Thanks for visiting! Feel free to <a href="mailto:[chernobayv05@gmail.com]" target="_blank" rel="noopener noreferrer">reach out</a> to connect.

# # =====================================================
# # üéì Education Section
# # =====================================================

education:
  - degree: "BEng (Hons) in Computer Engineering"
    school: "Toronto Metropolitan University"
    years: "2025 - Present"
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/TMU_logo.svg/1280px-TMU_logo.svg.png"

  - degree: "Ontario Secondary School Diploma (OSSD)"
    school: "Humberside Collegiate Institute"
    years: "2020 - 2022"
    logo: "/images/ntu_logo.svg"

# # =====================================================
# # üíº Work Experience Section
# # =====================================================

workExperience:
  - title: "Physical AI Lab Intern"
    company: "SAP"
    years: "Jan 2026 - Present"
    logo: "https://cubis.be/wp-content/uploads/2025/02/SAP_2011_logo.svg.png"

  - title: "Team Captain, Electrical & Strategy Lead"
    company: "FIRST Robotics - Team 9262"
    years: "August 2022 - July 2025"
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/FIRST_Logo.svg/250px-FIRST_Logo.svg.png"

  - title: "D-Shop Software Engineering Co-op Student"
    company: "SAP"
    years: "Jan 2024 ‚Äì Jul 2024"
    logo: "https://cubis.be/wp-content/uploads/2025/02/SAP_2011_logo.svg.png"

# # =====================================================
# # üé§ Presentations / Talks Section
# # =====================================================

talks:
  - category: "TD Synnex Gala"
    title: "How Robotics Education Shaped my Future"
    organization: "FIRST Canada"
    date: "Oct 15, 2025"
    link: "https://example.com/your-talk-link"
    image: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Example_image.svg"

  - category: "Workshop"
    title: "How to Network"
    organization: "University of Illinois Urbana-Champaign (UIUC)"
    date: "Sep 4, 2019"
    link: null
    image: "https://pm25.github.io/images/uiuc-workshop.webp"

  - category: "Podcast"
    title: "Practical Guide to PyTorch"
    organization: "ABC University"
    date: "Dec 5, 2022"
    link: "https://example.com/workshop-talk"
    image: null
    
  - category: "Podcast"
    title: "Practical Guide to PyTorch"
    organization: "ABC University"
    date: "Dec 5, 2022"
    link: "https://example.com/workshop-talk"
    image: null

# # =====================================================
# # üõ°Ô∏è Professional Services
# # =====================================================

services:
  - category: "Misc"
    role: "[Role]"
    organization: "[Organization]"
    date: "[Year]"
    link: "https://example.com/workshop-talk"
    image: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Example_image.svg"

  - category: "Research"
    role: "Reviewer"
    organization: "TPAMI 2024, NeurIPS 2025"
    date: "2024-2025"
    link: null
    image: null

  - category: "Research"
    role: "Program Committee Member"
    organization: "CVPR 2022"
    date: "2022"
    link: null
    image: null

  - category: "Teaching"
    role: "Teaching Assistant"
    organization: "National Taiwan University - Data Structures & Algorithms"
    date: "2021"
    link: null
    image: null

# # =====================================================
# # üõ†Ô∏è Skills Section
# # =====================================================

skills:
  Programming:
    - name: "[Name]"
      logo: "https://upload.wikimedia.org/wikipedia/commons/1/18/ISO_C%2B%2B_Logo.svg"
      proficiency: "[Proficiency]"
      description: "[Description]"

    - name: "Python"
      logo: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg"
      proficiency: Experienced
      description: null

    - name: "JavaScript"
      logo: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg"
      proficiency: Fluent
      description: null

  Web:
    - name: "React"
      logo: "https://upload.wikimedia.org/wikipedia/commons/3/30/React_Logo_SVG.svg"
      proficiency: Advanced
      description: null

    - name: "Typescript"
      logo: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Typescript.svg"
      proficiency: Fluent
      description: null

    - name: "TailwindCSS"
      logo: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Tailwind_CSS_Logo.svg"
      proficiency: Fluent
      description: null

    - name: "Next.js"
      logo: "https://logo.svgcdn.com/devicon/nextjs-original.png"
      proficiency: Fluent
      description: null

  Machine Learning:
    - name: "PyTorch"
      logo: "https://upload.wikimedia.org/wikipedia/commons/1/10/PyTorch_logo_icon.svg"
      proficiency: Experienced
      description: null

    - name: "TensorFlow"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg"
      proficiency: Fluent
      description: null

    - name: "Keras"
      logo: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Keras_logo.svg"
      proficiency: Fluent
      description: null

  Research:
    - name: "Machine Learning"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/OOjs_UI_icon_academic-progressive.svg"
      proficiency: 2020 - Current
      description: "General machine learning methods and applied research."

    - name: "Representation Learning"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/OOjs_UI_icon_academic-progressive.svg"
      proficiency: 2024 - 2025
      description: "Learning meaningful embeddings and feature representations from data."

  Language:
    - name: "English"
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/OOjs_UI_icon_language-ltr-progressive.svg"
      proficiency: Fluent
      description: "Professional working proficiency."

    - name: "Taiwanese Hokkien"
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/OOjs_UI_icon_language-ltr-progressive.svg"
      proficiency: Native
      description: "Native fluency."
