# =====================================================
# Website Configuration
# This section contains general information about your website.
# =====================================================

site:
  name: "Victoria's Portfolio"
  repoUrl: "https://github.com/chernobayv/portfolio"
  description: "A portfolio of my career journey"
  author: "Victoria Chernobay"
